### ISSUE TITLE
Problem compiling amber_vins

### ISSUE THREAD

**Issue by sunghoon031** [paulyang1990/my_VINS#1]
I get errors when compiling amber_vins: it complains about conservativeResize function.

Is this project still ongoing btw?

**Comment by ShuoYangRobotics** [comment]
This functions belongs to an experimental version of Eigen,
you can change it into "resize" safely.

The project is almost finish since it is used to demonstrate VO functionality only. To make a complete system, a lot of extra efforts are needed.

**Comment by wk199** [comment]
Hi!
Does this project complete the whole MSCKF?  How is the result of experiment ?

**Comment by ShuoYangRobotics** [comment]
This project complete the whole MSCKF. 
The result of simulation is satisfactory. 
However,  you may not know that "the whole MSCKF" is not complete. The initialization of first a few states is very very difficult. In my simulation experiment, I manually set initial values to be true values. But in real experiment, I cannot do so, so my MSCKF never run. 

The initialization process, admitted by MSCKF original author (I have a conversation with him a few months ago), is not described in the paper.

**Comment by wk199** [comment]
Thank you for your reply, I understand what you mean. Before  I have tried to run the other MSCKF code with the experimental data , the result of experiment is not satisfactory because of the reason you say. The MSCKF2.0 admitted by Li MingYang seems to give a good solution for the initialization. I am looking forward you can get a good result.

**Comment by wk199** [comment]
Hi! I have got much from your code. But I don't got a satisfactory result in the simulation, can you give me some help? The intriniscs of camera you set is real parameter, how to set in simulation?Thanks.

**Comment by ShuoYangRobotics** [comment]
are you using amber_vins?
